<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Slotwise.ServiceDefaults\Slotwise.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Slotwise.SharedKernel\Slotwise.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Slotwise.Api.IntegrationTests" />
  </ItemGroup>

</Project>
